name: Continuous Delivery
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'README.md'

jobs:
  build-and-test:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit

  release:
    name: Release
    needs:
      - build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Install semantic-release
        run: npm i semantic-release --save-dev
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
